### ISSUE TITLE
Fix migration.

### ISSUE THREAD

**Issue by pama** [devinaflynn/flyy2#3]
When I run `rake db:migrate` I get:

```
Paulos-MBP:flyy2 pama$ rake db:migrate
rake aborted!
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/fog-core-1.24.0/lib/fog/core/service.rb:237:in `validate_options'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/fog-core-1.24.0/lib/fog/core/service.rb:261:in `handle_settings'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/fog-core-1.24.0/lib/fog/core/service.rb:98:in `new'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/fog-core-1.24.0/lib/fog/storage.rb:26:in `new'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:83:in `eager_load_fog'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:96:in `fog_credentials='
/Users/pama/projects/mentoring/devin-flynm/flyy2/config/initializers/carrierwave.rb:2:in `block in <top (required)>'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:118:in `configure'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/carrierwave-0.10.0/lib/carrierwave.rb:14:in `configure'
/Users/pama/projects/mentoring/devin-flynm/flyy2/config/initializers/carrierwave.rb:1:in `<top (required)>'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `block in load'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/engine.rb:647:in `load_config_initializer'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/engine.rb:611:in `each'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `instance_exec'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `run'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/initializable.rb:44:in `each'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/initializable.rb:54:in `run_initializers'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/application.rb:288:in `initialize!'
/Users/pama/projects/mentoring/devin-flynm/flyy2/config/environment.rb:5:in `<top (required)>'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/application.rb:264:in `require_environment!'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/gems/railties-4.1.1/lib/rails/application.rb:367:in `block in run_tasks_blocks'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/bin/ruby_executable_hooks:15:in `eval'
/Users/pama/.rvm/gems/ruby-2.1.5@flyy2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by pama** [comment]
This issue is related with amazon s3 configuration.
